services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./public
        target: /usr/share/nginx/html
        read_only: true
        bind:
          create_host_path: false
    labels:
      - traefik.enable=true
      - traefik.http.routers.majo.rule=Host(`${MAJO_DOMAIN}`) || Host(`www.${MAJO_DOMAIN}`)
      - traefik.http.routers.majo.entrypoints=websecure
      - traefik.http.routers.majo.tls=true
      - traefik.http.routers.majo.tls.certresolver=letsencrypt
      - traefik.http.services.majo.loadbalancer.server.port=80
